= Domain, API, DTO

**Translating between layers with Chimney**

---

Mateusz Kubuszok

== About me

[%step]
* breaking things in Scala for 9 years
* a little bit of open source - including co-authoring Chimney for almost 7 years now
* blog at https://kubuszok.com[Kubuszok.com]
* niche https://leanpub.com/jvm-scala-book[Things you need to know about JVM (that matter in Scala)] ebook

[NOTE.speaker]
--
Chimney is 7 years next month
--

== Once upon a time

[%step]
* simple web backend
* Circe codecs
* Doobie (well, Slick actually)
* Protobuf and Kinesis (well, it was Avro and Postgres)

[NOTE.speaker]
--
It was long time ago, so let's use some modern stack as an example
--

=== !

Let's look at example

[NOTE.speaker]
--
example1.scala
--

=== !

It kinds works, but let add a few modifications:

[%step]
* for `creationDate` let's use `Instant``
* for `id` let's use `UUID`

[NOTE.speaker]
--
example2.scala
--

=== !

We can still improve it!

[%step]
* let's create a separate model for JSONs
* let's create a separate model for DB operations

[NOTE.speaker]
--
example3.scala
--

=== !

Could we get rid of the silly code for mapping?

=== !

YES

[NOTE.speaker]
--
example4.scala
--

== What is possible with Chimney?

=== case class to case class

[%step]
[source,scala]
--
case class Source(a: Int, b: String, c: Boolean)
case class Target(b: String, a: Int)

import io.scalaland.chimney.dsl.*
Source(777, "value", c = true).transformInto[Target]
// Target("value", 777)
--

[%step]
[source,scala]
--
case class Source(a: Int, b: String)
case class Target2(b: String, a: Int, extra: Double)

import io.scalaland.chimney.dsl.*
Source(777, "value").into[Target2]
  .withFieldConst(_.extra, 3.14) 
  .transform // Target2("value", 777, 3.14)
Source(777, "value").into[Target2]
  .withFieldComputed(_.extra, src => src.a.toDouble) 
  .transform // Target2("value", 777, 777.0)
--

=== ADT to ADT

[%step]
[source,scala]
--
enum Source:
  case Foo, Bar(b: Int)
enum Target:
  case Foo, Bar(b: Int), Baz

import io.scalaland.chimney.dsl.*
(Source.Bar(777): Source).transformInto[Target]
// Target.Bar(777)
--

[%step]
[source,scala]
--
enum Source:
  case Foo, Bar(b: Int), Baz
enum Target:
  case Foo, Bar(b: Int)

import io.scalaland.chimney.dsl.*
(Source.Baz: Source).into[Target]
  .withEnumCaseHandled[Source.Baz](_ => Target.Foo)
  .transform // Target.Foo
--

=== Collections

[%step]
[source,scala]
--
case class Source(a: Int, b: String, c: Boolean)
case class Target(b: String, a: Int)

import io.scalaland.chimney.dsl.*
List(Source(777, "value")).transformInto[Vector[Target]]
// Vector(Target("value", 777))
--

[%step]
[source,scala]
--
case class Source(a: Int, b: String)
case class Target2(b: String, a: Int, extra: Double)

import io.scalaland.chimney.dsl.*
List(Source(777, "value")).into[Vector[Target]]
  .withFieldConst(_.eachItem.extra, 3.14)
  .transform // Vector(Target("value", 777, 3.14))
--

== More info

* https://chimney.readthedocs.io
* https://github.com/scalalandio/chimney

== Thank you !
